<?php

namespace SchoolBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query\ResultSetMapping;
use Doctrine\ORM\Query\ResultSetMappingBuilder;

/**
 * GameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MatiereRepository extends EntityRepository
{

    /**
     *
     */
    public function findAll()
    {
        $sql =  "SELECT * FROM c3csi_matiere m";

        $rsm = new ResultSetMapping();
        $rsm->addEntityResult('SchoolBundle\Entity\Matiere', 'm');
        $rsm->addFieldResult('m', 'id', 'id');
        $rsm->addFieldResult('m', 'name', 'name');

        $query = $this->_em->createNativeQuery($sql, $rsm);
        $matieres = $query->getResult();

        return $matieres;
    }

    /**
     * @param $id
     */
    public function findOneById($id, $fullObject=true)
    {
        $sql =  "SELECT *".
                "FROM c3csi_matiere m WHERE id = ?";

        $rsm = new ResultSetMapping();
        $rsm->addEntityResult('SchoolBundle\Entity\Matiere', 'm');
        $rsm->addFieldResult('m', 'id', 'id');
        $rsm->addFieldResult('m', 'name', 'name');

        $query = $this->_em->createNativeQuery($sql, $rsm);
        $query->setParameter(1, $id);
        $result = $query->getResult();

        if(isset($result[0])){
            return $result[0];
        }
        return $result;
    }

    /**
     *
     *
     * @param $playerID
     * @return array
     */
    public function findMatieresByIntervenant($intervenantID)
    {

        $sql =  "SELECT mat.id, mat.name ".
                "FROM c3csi_enseignement ens ".
                "LEFT JOIN c3csi_matiere mat ON mat.id = ens.matiere_id ".
                "WHERE ens.intervenant_id = ?";

        $rsm = new ResultSetMapping();
        $rsm->addEntityResult('SchoolBundle\Entity\Matiere' , 'mat');
        $rsm->addFieldResult('mat', 'id', 'id');
        $rsm->addFieldResult('mat', 'name', 'name');

        $query = $this->_em->createNativeQuery($sql, $rsm);
        $query->setParameter(1, $intervenantID);
        $result = $query->getResult();

        return $result;
    }

}
