<?php

namespace EvaluationBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query\ResultSetMapping;
use Doctrine\ORM\Query\ResultSetMappingBuilder;

/**
 * GameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExamenRepository extends EntityRepository
{

    /**
     * Returns all examens
     */
    public function findAll()
    {
        $sql =  "SELECT * ".
                "FROM c3csi_examen m";

        $rsm = new ResultSetMapping();
        $rsm->addEntityResult('EvaluationBundle\Entity\Examen', 'e');
        $rsm->addFieldResult('e', 'id', 'id');
        $rsm->addFieldResult('e', 'name', 'name');
        $rsm->addFieldResult('e', 'description', 'description');

        $query = $this->_em->createNativeQuery($sql, $rsm);
        $matieres = $query->getResult();

        return $matieres;
    }

    /**
     * Returns a specific examen
     *
     * @param $id
     */
    public function findOneById($id, $fullObject=true)
    {
        $sql =  "SELECT * ".
                "FROM c3csi_examen m WHERE id = ?";

        $rsm = new ResultSetMapping();
        $rsm->addEntityResult('EvaluationBundle\Entity\Examen', 'm');
        $rsm->addFieldResult('m', 'id', 'id');
        $rsm->addFieldResult('m', 'name', 'name');

        $query = $this->_em->createNativeQuery($sql, $rsm);
        $query->setParameter(1, $id);
        $result = $query->getResult();

        if(isset($result[0])){
            return $result[0];
        }
        return $result;
    }

    /**
     * Returns the examens related to the group passed in parameter
     *
     * @param $groupID
     */
    public function findByGroupId($groupID) {
        $sql =  "SELECT exam.id, exam.name, exam.description, exam.date ".
                "FROM c3csi_group grp ".
                "LEFT JOIN c3csi_examen exam ON exam.group_id = grp.id ".
                "WHERE grp.id = ? ".
                "ORDER BY date DESC";

        $rsm = new ResultSetMapping();
        $rsm->addEntityResult('EvaluationBundle\Entity\Examen', 'm');
        $rsm->addFieldResult('m', 'id', 'id');
        $rsm->addFieldResult('m', 'name', 'name');
        $rsm->addFieldResult('m', 'description', 'description');
        $rsm->addFieldResult('m', 'date', 'date');

        $query = $this->_em->createNativeQuery($sql, $rsm);
        $query->setParameter(1, $groupID);
        $result = $query->getResult();

        return $result;
    }

    /**
     * Returns the examens related to the group passed in parameter
     *
     * @param $groupID
     */
    public function findByUserId($userID) {
        $sql =  "SELECT exam.id, exam.name, exam.description, exam.date ".
            "FROM c3csi_user u ".
            "LEFT JOIN c3csi_group_rel_user grus ON grus.user_id = u.id ".
            "LEFT JOIN c3csi_examen exam ON exam.group_id = grus.group_id ".
            "WHERE u.id = ? ".
            "ORDER BY date DESC";

        $rsm = new ResultSetMapping();
        $rsm->addEntityResult('EvaluationBundle\Entity\Examen', 'm');
        $rsm->addFieldResult('m', 'id', 'id');
        $rsm->addFieldResult('m', 'name', 'name');
        $rsm->addFieldResult('m', 'description', 'description');
        $rsm->addFieldResult('m', 'date', 'date');

        $query = $this->_em->createNativeQuery($sql, $rsm);
        $query->setParameter(1, $userID);
        $result = $query->getResult();

        return $result;
    }

    /**
     * @param $userID
     * @return array
     */
    public function findForCalendarByUserId($userID){
        $sql =  "SELECT exam.id as exam_id, exam.name as exam_name, exam.description, exam.date as exam_date ".
            "FROM c3csi_user u ".
            "LEFT JOIN c3csi_group_rel_user grus ON grus.user_id = u.id ".
            "LEFT JOIN c3csi_examen exam ON exam.group_id = grus.group_id ".
            "WHERE u.id = ? ".
            "ORDER BY date DESC";

        $rsm = new ResultSetMapping();
        $rsm->addScalarResult("exam_name", "title");
        $rsm->addScalarResult("exam_date", "start");
        $rsm->addScalarResult(true, "allDay");

        $query = $this->_em->createNativeQuery($sql, $rsm);
        $query->setParameter(1, $userID);
        $result = $query->getResult(\Doctrine\ORM\Query::HYDRATE_ARRAY);

        return $result;
    }

    /**
     * Returns the examens related to the intervenant passed in parameter
     *
     * @param $intervenantID
     */
    public function findByIntervenantId($intervenantID) {
        $sql =  "SELECT exam.id, exam.name, exam.description, exam.date ".
                "FROM c3csi_user user ".
                "LEFT JOIN c3csi_examen exam ON exam.intervenant_id = user.id ".
                "WHERE user.id = ? ".
                "ORDER BY date DESC";

        $rsm = new ResultSetMapping();
        $rsm->addEntityResult('EvaluationBundle\Entity\Examen', 'm');
        $rsm->addFieldResult('m', 'id', 'id');
        $rsm->addFieldResult('m', 'name', 'name');
        $rsm->addFieldResult('m', 'description', 'description');
        $rsm->addFieldResult('m', 'date', 'date');

        $query = $this->_em->createNativeQuery($sql, $rsm);
        $query->setParameter(1, $intervenantID);
        $result = $query->getResult();

        return $result;
    }

}
