<?php

namespace EvaluationBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query\ResultSetMapping;
use Doctrine\ORM\Query\ResultSetMappingBuilder;

/**
 * GameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExamenRepository extends EntityRepository
{

    /**
     *
     */
    public function findAll()
    {
        $sql =  "SELECT * ".
                "FROM c3csi_examen m";

        $rsm = new ResultSetMapping();
        $rsm->addEntityResult('EvaluationBundle\Entity\Examen', 'e');
        $rsm->addFieldResult('e', 'id', 'id');
        $rsm->addFieldResult('e', 'name', 'name');

        $query = $this->_em->createNativeQuery($sql, $rsm);
        $matieres = $query->getResult();

        return $matieres;
    }

    /**
     * @param $id
     */
    public function findOneById($id, $fullObject=true)
    {
        $sql =  "SELECT *".
                "FROM c3csi_examen m WHERE id = ?";

        $rsm = new ResultSetMapping();
        $rsm->addEntityResult('EvaluationBundle\Entity\Examen', 'm');
        $rsm->addFieldResult('m', 'id', 'id');
        $rsm->addFieldResult('m', 'name', 'name');

        $query = $this->_em->createNativeQuery($sql, $rsm);
        $query->setParameter(1, $id);
        $result = $query->getResult();

        if(isset($result[0])){
            return $result[0];
        }
        return $result;
    }

}
